Improve script interface

diff --git a/script/server b/script/server
--- a/script/server
+++ b/script/server
@@ -19,7 +19,7 @@ readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && \
 
 usage() {
   die "$(cat <<END
-usage: ${SCRIPT_NAME} down | up|restart [environment] [build]
+usage: ${SCRIPT_NAME} down | up [environment] [build]
 
 environment can be:
   -d    development, default
@@ -73,7 +73,10 @@ parse_args() {
     environment=-d
   fi
   if [[ -z "${build}" ]]; then
-    build=dev
+    case "${environment}" in 
+      -d) build=dev ;;
+      -s|-p) build=prod ;;
+    esac
   fi
 
   log "arguments (\
@@ -81,6 +84,14 @@ cmd: ${cmd}, \
 environment: ${environment}, \
 build: ${build}\
 )"
+}
+
+compose_down() {
+  if is_compose_up; then
+    logfun docker-compose \
+      -f docker-compose.yml \
+      -f build/docker-compose.dev.yml down
+  fi
 }
 
 main() {
@@ -92,18 +103,26 @@ main() {
     up)
       case "${environment}" in
         -d)
+          script/server down
           script/build "${build}"
-          logfun docker-compose \
-            -f docker-compose.yml \
-            -f "build/docker-compose.${build}.yml" \
-            -f build/docker-compose.dev.secrets.yml \
-            up -d
+          set +e
+            logfun docker-compose \
+              -f docker-compose.yml \
+              -f "build/docker-compose.${build}.yml" \
+              -f build/docker-compose.dev.secrets.yml \
+              up -d
+            result="$?"
+          set -e
+          if [[ "${result}" -eq 1 ]]; then
+            die "error starting: have you run the setup script?"
+          fi
           ;;
         -s)
           if [[ "${build}" == "dev" ]]; then
             log "warning: ignoring build option and using production image" \
               "anyway"
           fi
+          compose_down
           logfun docker stack deploy \
             -c docker-compose.yml \
             -c build/docker-compose.prod.yml \
@@ -112,9 +131,10 @@ main() {
           ;;
         -p)
           if [[ "${build}" == "dev" ]]; then
-            echo "warning: ignoring build option and using production image" \
+            log "warning: ignoring build option and using production image" \
               "anyway"
           fi
+          compose_down
           logfun sudo docker stack deploy \
             -c docker-compose.yml \
             -c build/docker-compose.prod.yml \
@@ -125,14 +145,7 @@ main() {
       ;;
     down)
       logfun docker stack rm ${STACK_NAME}
-      sleep 4
-      logfun  docker-compose \
-        -f docker-compose.yml \
-        -f build/docker-compose.dev.yml down
-      ;;
-    restart)
-      script/server down
-      script/server up "${environment}" "${build}"
+      compose_down
       ;;
     *)
       usage
